USE `forum`;

CREATE TABLE IF NOT EXISTS users (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(255) COLLATE utf8mb4_0900_ai_ci NOT NULL,
	firstname VARCHAR(255) COLLATE utf8mb4_0900_ai_ci NOT NULL,
	lastname VARCHAR(255) COLLATE utf8mb4_0900_ai_ci NOT NULL,
	birthday DATE NOT NULL,
	email VARCHAR(255) COLLATE utf8mb4_0900_ai_ci NOT NULL UNIQUE,
	backup_email VARCHAR(255) COLLATE utf8mb4_0900_ai_ci NOT NULL,
	password VARCHAR(255) COLLATE utf8mb4_0900_ai_ci NOT NULL,
	remember_token TEXT COLLATE utf8mb4_0900_ai_ci NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	registered_at TIMESTAMP NOT NULL
);
